
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 18 22:25:33 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 17;
  public static final int CONST = 9;
  public static final int PERIOD = 47;
  public static final int LGT = 35;
  public static final int NUMCONST = 4;
  public static final int RIGHTBRACKET = 18;
  public static final int CONTINUE = 23;
  public static final int RIGHTBRACKET_CUR = 8;
  public static final int MINUS = 40;
  public static final int LGTEQ = 36;
  public static final int LLTEQ = 38;
  public static final int SEMICOLON = 11;
  public static final int RECORD = 16;
  public static final int COMMA = 12;
  public static final int LEFTBRACKET_CUR = 7;
  public static final int CLASS = 15;
  public static final int INC = 27;
  public static final int DIV = 42;
  public static final int PLUS = 39;
  public static final int ASSIGN = 10;
  public static final int IF = 19;
  public static final int THIS = 49;
  public static final int LEFTBRACKET_SQ = 13;
  public static final int EOF = 0;
  public static final int LAND = 30;
  public static final int RETURN = 24;
  public static final int LLT = 37;
  public static final int SUPER = 48;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PROGRAM = 6;
  public static final int MUL = 41;
  public static final int LOR = 29;
  public static final int MOD = 43;
  public static final int BREAK = 22;
  public static final int IDENT = 2;
  public static final int VOID = 45;
  public static final int COLON = 32;
  public static final int ELSE = 46;
  public static final int ENUM = 50;
  public static final int READ = 25;
  public static final int GOTO = 51;
  public static final int CHARCONST = 5;
  public static final int WHILE = 21;
  public static final int LNEQ = 34;
  public static final int EXTENDS = 44;
  public static final int BOOLCONST = 3;
  public static final int LEQ = 33;
  public static final int DEC = 28;
  public static final int RIGHTBRACKET_SQ = 14;
  public static final int PRINT = 26;
  public static final int DO = 20;
}

